name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Run tests
        uses: actions/checkout@v3
      run: xcodebuild test -scheme "takehome" -destination "platform=iOS Simulator,name=iPhone 14"
