name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Force Xcode 14
      run: sudo xcode-select -switch /Applications/Xcode_14.1.app
    - name: Run tests
      run: xcodebuild clean test -project "takehome.xcodeproj" -scheme "takehome" -destination "platform=iOS Simulator,name=iPhone 13 Pro Max,OS=latest"
    - name: Build App
      run: xcodebuild -project "takehome.xcodeproj" -scheme "takehome" -destination "generic/platform=iOS" 
